### ISSUE TITLE
Device not connecting on either linux or windows

### ISSUE THREAD

**Issue by madaerodog** [ganzziani/xscopes-qt#26]
Hello, I have compiled the app on linux, but when I try to connect the device via USB the app sees the cable but when I press connect, I get 2/3 seconds of grey app and then nothing, no device found. I have executed the USBfix.sh but no luck, any idea?

I also have the bluetooth addon and tried the download precompiled app for both windows and linux from the main page but no luck. The device (XMEGA Xprotolab) does work on a old windows app that I found and it's missing a few options, so there is no problem with the device.

Thank you,
Constantin

**Comment by ganzziani** [comment]
I not a Linux user, but there are some that have provided tips and suggestions on my website:
http://www.gabotronics.com/product-info/xprotolab-pc-interface.htm

**Comment by madaerodog** [comment]
Read through it until the final comment, I find myself in the position of this user also:
"Having same problem. I'm just looking to run a precompiled version of the software and can't seem to find a single working solution for the Linux/Ubuntu platform. Can you direct me to the old software package so I can at least use that?"

But what about on windows? Do you have a compiled version that works? Thank you.

**Comment by ganzziani** [comment]
If you need the installer, they are on the same page. Click on the windows icon.

**Comment by julianstirling** [comment]
For linux the pre-compiled solution won't work. Someone would need to make a .deb. I have added a step by step guide to install on Ubuntu to the forum:
https://www.gabotronics.com/component/option,com_ccboard/Itemid,12/forum,15/topic,314/view,postlist/
this uses ewisuri's fork on github as this solves bugs which stop Xscope compiling on linux.

Ganzziani, have you tried compiling [ewisuri's fork](https://github.com/ewisuri/xscopes-qt) on Windows? I would try but I have no Windows machines. If it works it may be an idea to merge it into your master so it can be compiled cross platform.

**Comment by rzr** [comment]
I could help to share a deb to community , but I have no device to test it

**Comment by mibs510** [comment]
I made a 64bit Debian/Ubuntu package. More here: http://osmar.gonzal.us/xscopes-qt-debianubuntu-packages/
