### ISSUE TITLE
Need Qt5Network to sucessfully build

### ISSUE THREAD

**Issue by ghostshadow** [ganzziani/xscopes-qt#41]
The Qt5Network headers and libraries need to be made available in the CMakeLists.txt to successfully build the project.

**Comment by rzr** [comment]
Is app using network ?

btw, ping me and I will update the debian packages

**Comment by ghostshadow** [comment]
As mentioned in the pull request, the filedownload code uses network. And as far as a short search got me, the only thing using the filedownloader is the USB bootloader code.
So either the network lib has to be available or the filedownloader needs to be excluded.
